export const styles = {
    card: {
        maxWidth: 380,
        margin: "2rem auto",
        background: "#fff",
        border: "1px solid #e5e7eb",
        borderRadius: 16,
        padding: "2rem 1.75rem",
        fontFamily: "'DM Sans', sans-serif",
    },
    title: {
        fontSize: 20,
        fontWeight: 600,
        color: "#111827",
        margin: "0 0 6px",
    },
    subtitle: {
        fontSize: 14,
        color: "#6b7280",
        margin: "0 0 1.25rem",
        lineHeight: 1.5,
    },
    otpRow: {
        display: "flex",
        gap: 8,
        alignItems: "center",
        marginBottom: "0.75rem",
    },
    otpInput: {
        width: 44,
        height: 48,
        border: "1px solid #d1d5db",
        borderRadius: 10,
        textAlign: "center",
        fontSize: 18,
        fontWeight: 600,
        color: "#111827",
        outline: "none",
        background: "#fff",
    },
    dot: {
        fontSize: 20,
        color: "#9ca3af",
        userSelect: "none",
    },
    verifiedRow: {
        display: "flex",
        alignItems: "center",
        gap: 6,
        fontSize: 13,
        minHeight: 24,
        marginBottom: "1rem",
    },
    verifiedText: {
        color: "#1D9E75",
        fontWeight: 500,
    },
    divider: {
        border: "none",
        borderTop: "1px solid #f3f4f6",
        margin: "0 0 1.25rem",
    },
    fieldLabel: {
        display: "block",
        fontSize: 13,
        fontWeight: 500,
        color: "#374151",
        marginBottom: 6,
    },
    pwWrap: {
        position: "relative",
        marginBottom: 0,
    },
    pwInput: {
        width: "100%",
        boxSizing: "border-box",
        height: 42,
        border: "1px solid #d1d5db",
        borderRadius: 10,
        padding: "0 42px 0 12px",
        fontSize: 14,
        color: "#111827",
        background: "#fff",
        outline: "none",
    },
    eyeBtn: {
        position: "absolute",
        right: 10,
        top: "50%",
        transform: "translateY(-50%)",
        background: "none",
        border: "none",
        cursor: "pointer",
        color: "#9ca3af",
        padding: 0,
        display: "flex",
        alignItems: "center",
    },
    ruleList: {
        listStyle: "none",
        padding: 0,
        margin: "12px 0 1.5rem",
        display: "flex",
        flexDirection: "column",
        gap: 6,
    },
    rule: (pass) => ({
        display: "flex",
        alignItems: "center",
        gap: 8,
        fontSize: 13,
        color: pass ? "#1D9E75" : "#9ca3af",
    }),
    btnRow: {
        display: "flex",
        gap: 10,
    },
    cancelBtn: {
        flex: 1,
        height: 40,
        background: "#fff",
        border: "1px solid #d1d5db",
        borderRadius: 10,
        cursor: "pointer",
        fontSize: 14,
        color: "#374151",
        fontWeight: 500,
    },
    submitBtn: (active) => ({
        flex: 2,
        height: 40,
        background: active ? "#1D9E75" : "#f3f4f6",
        border: "none",
        borderRadius: 10,
        cursor: active ? "pointer" : "not-allowed",
        fontSize: 14,
        color: active ? "#fff" : "#9ca3af",
        fontWeight: 500,
        transition: "background 0.15s, color 0.15s",
    }),
};

