export const styles = {
    eyeBtn: {
        position: "absolute",
        right: 10,
        top: "50%",
        transform: "translateY(-50%)",
        background: "none",
        border: "none",
        cursor: "pointer",
        color: "#9ca3af",
        padding: 0,
        display: "flex",
        alignItems: "center",
    },
    ruleList: {
        listStyle: "none",
        padding: 0,
        margin: "12px 0 1.5rem",
        display: "flex",
        flexDirection: "column",
        gap: 6,
    },
    rule: (pass) => ({
        display: "flex",
        alignItems: "center",
        gap: 8,
        fontSize: 13,
        color: pass ? "#1D9E75" : "#9ca3af",
    }),
};
